# Generated by Django 4.2.5 on 2024-01-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0007_cart_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='image',
            field=models.ImageField(upload_to='my_data'),
        ),
    ]
