# Generated by Django 4.2.5 on 2023-12-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsmodel',
            name='work_position',
            field=models.CharField(default='designer', max_length=40),
        ),
    ]
