# Generated by Django 4.2.5 on 2023-12-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0002_jobsmodel_work_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='work_position',
            field=models.CharField(max_length=40),
        ),
    ]
