# Generated by Django 4.2.5 on 2024-01-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0010_alter_jobsmodel_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsmodel',
            name='email',
            field=models.EmailField(default='admin@gmail.com', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobsmodel',
            name='phone_number',
            field=models.CharField(default='0 999 999 999', max_length=15),
            preserve_default=False,
        ),
    ]
