# Generated by Django 4.2.5 on 2024-03-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0012_alter_jobsmodel_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
