# Generated by Django 4.2.5 on 2024-03-20 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0014_alter_jobsmodel_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='salary',
            field=models.DecimalField(decimal_places=0, max_digits=19, validators=[django.core.validators.MaxValueValidator(9999999999999999)]),
        ),
    ]
