# Generated by Django 4.2.5 on 2024-03-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0021_alter_jobsmodel_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsmodel',
            name='country',
            field=models.CharField(default='The United States', max_length=50),
            preserve_default=False,
        ),
    ]
