# Generated by Django 5.0.3 on 2024-04-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_app", "0022_jobsmodel_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobsmodel",
            name="city",
            field=models.CharField(default="City", max_length=50),
        ),
    ]
