# Generated by Django 5.0.3 on 2024-04-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_app", "0023_jobsmodel_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobsmodel",
            name="city",
            field=models.CharField(max_length=50),
        ),
    ]
